baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Art'
pageRef = '/art'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 24

[[menus.main]]
name = 'Comic'
pageRef = '/comic'
weight = 26

[[menus.main]]
name = 'Video'
pageRef = '/video'
weight = 28

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Tools'
pageRef = '/tools'
weight = 32

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
